language: objective-c
osx_image: xcode8.2
xcode_project: Jasmine.xcworkspace
xcode_scheme: Jasmine
xcode_sdk: iphonesimulator10.0
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Jasmine.xcworkspace -scheme Jasmine CODE_SIGNING_REQUIRED=NO